#!/bin/bash

echo " Please enter your name:"
read name
echo " your name is: ${name}"
echo " Please enter your password:"
read password
echo " your password is: ${password}"
echo "please enter your 2nd username:"
read -s username
echo "your 2nd name is: ${username}"
echo "please provide your 2nd password:"
read -s pwd
echo "your 2nd password is :${pwd}"
